=== salfter/openemulator/libemulation/edl-1.0.dtd
<!--
   Emulation Description Language version 1.0 DTD

   For further information, see: http://www.openemulator.org

   Copyright (c) 2010-2011 Marc S. Ressl,
   All Rights Reserved. 

   This DTD module is identified by the PUBLIC and SYSTEM identifiers:

   PUBLIC "-//W3C//DTD EDL 1.0//EN"
   SYSTEM "http://www.openemulator.org/DTD/edl-1.dtd"

   $Revision: 0.8 $
   $Date: 2011/09/10 17:00:00-0300 $
-->

<!ELEMENT edl (device*|port*|connector*|component*)>
<!ATTLIST edl version CDATA "1.0">
<!ATTLIST edl generator CDATA #REQUIRED>
<!ATTLIST edl framework CDATA #REQUIRED>
<!ATTLIST edl label CDATA #IMPLIED>
<!ATTLIST edl image CDATA #IMPLIED>
<!ATTLIST edl description CDATA #IMPLIED>

<!ELEMENT device (setting*)>
<!ATTLIST device id ID #REQUIRED>
<!ATTLIST device label CDATA #REQUIRED>
<!ATTLIST device image CDATA #IMPLIED>

<!ELEMENT setting EMPTY>
<!ATTLIST setting ref IDREF #REQUIRED>
<!ATTLIST setting name CDATA #REQUIRED>
<!ATTLIST setting label CDATA #REQUIRED>
<!ATTLIST setting type CDATA #REQUIRED>
<!ATTLIST setting options CDATA #IMPLIED>

<!ELEMENT port (inlet*)>
<!ATTLIST port id ID #REQUIRED>
<!ATTLIST port ref CDATA #REQUIRED>
<!ATTLIST port type CDATA #REQUIRED>
<!ATTLIST port group CDATA #IMPLIED>
<!ATTLIST port label CDATA #REQUIRED>
<!ATTLIST port image ID #IMPLIED>

<!ELEMENT connector (inlet*)>
<!ATTLIST connector id ID #REQUIRED>
<!ATTLIST connector type CDATA #REQUIRED>

<!ELEMENT inlet EMPTY>
<!ATTLIST inlet ref IDREF #REQUIRED>
<!ATTLIST inlet property CDATA #REQUIRED>
<!ATTLIST inlet outletRef CDATA #REQUIRED>

<!ELEMENT component (property*)>
<!ATTLIST component id ID #REQUIRED>
<!ATTLIST component class CDATA #REQUIRED>

<!ELEMENT property (setting*)>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #IMPLIED>
<!ATTLIST property ref CDATA #IMPLIED>
<!ATTLIST property src CDATA #IMPLIED>

=== salfter/openemulator/library/Apple II/Apple Language Card.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" label="Apple Language Card" image="images/Apple/Apple Language Card.png" description="The Apple Language Card is a 16 kiB memory expansion for the Apple II and Apple II+ computers. It is required for running Apple Pascal and ProDOS. It must be installed in slot 0.">

<device id="appleLanguageCard" label="Apple Language Card" image="images/Apple/Apple Language Card.png" group="expansions" />
<connector id="appleLanguageCard.connector" ref="" type="Apple II Slot" label="Connector" >
    <inlet ref="appleLanguageCard.io" property="mmu" outletRef="mmu" />
</connector>
<component id="appleLanguageCard.io" class="AppleLanguageCard">
    <property name="mmu" ref="" />
</component>
<component id="appleLanguageCard.memoryOffset" class="MemoryOffset">
    <property name="component" ref="appleLanguageCard.memory" />
</component>
<component id="appleLanguageCard.memory" class="RAM">
    <property name="host" ref="host" />
    <property name="size" value="16384" />
    <property name="image" src="${packagePath}/${id}.bin" />
</component>

</edl>

=== salfter/openemulator/library/Monitors/Apple Monitor II.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE EDL PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" creator="OpenEmulator" framework="787" label="Apple Monitor II" image="images/Apple/Apple Monitor II.png" description="The Apple Monitor II is a CRT-based green monochrome 12-inch monitor manufactured by Apple Computer for the Apple II personal computer family.">
    
    <device id="appleMonitorII" label="Apple Monitor II" image="images/Apple/Apple Monitor II.png">
        <setting ref="appleMonitorII.monitor" name="videoBrightness" label="Brightness" type="slider" options="-1.0,1.0"/>
        <setting ref="appleMonitorII.monitor" name="videoContrast" label="Contrast" type="slider" options="0.0,1.0"/>
        <setting ref="appleMonitorII.monitor" name="videoVerticalCenter" label="Vertical Center" type="slider" options="-0.1,0.1"/>
        <setting ref="appleMonitorII.monitor" name="videoVerticalSize" label="Vertical Size" type="slider" options="0.85,1.25"/>
    </device>
    <connector id="appleMonitorII.connector" type="Composite Video Port">
        <inlet ref="appleMonitorII.monitor" property="controlBus" outletRef="controlBus"/>
    </connector>
    <component id="appleMonitorII.monitor" class="Monitor">
        <property name="device" ref="appleMonitorII"/>
        <property name="controlBus" ref=""/>
        <property name="videoDecoder" value="Monochrome"/>
        <property name="videoBrightness" value="0.15"/>
        <property name="videoContrast" value="0.8"/>
        <property name="videoSaturation" value="1.45"/>
        <property name="videoHue" value="0.27"/>
        <property name="videoHorizontalCenter" value="0"/>
        <property name="videoHorizontalSize" value="1.05"/>
        <property name="videoVerticalCenter" value="0"/>
        <property name="videoVerticalSize" value="1.05"/>
        <property name="videoBandwidth" value="6000000"/>
        <property name="displayBarrel" value="0.1"/>
        <property name="displayScanlineLevel" value="0.5"/>
        <property name="displayCenterLighting" value="0.5"/>
        <property name="displayLuminanceGain" value="1.5"/>
    </component>
    
</edl>

=== salfter/openemulator/library/Monitors/AppleColor Composite Monitor IIe.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" generator="OpenEmulator" build="736" label="AppleColor Composite Monitor IIe" image="images/Apple/AppleColor Composite Monitor IIe.png" description="The AppleColor Composite Monitor IIe is a CRT-based color 13-inch monitor manufactured by Apple Computer for the Apple II personal computer family.">
    
    <device id="appleColorCompositeMonitorIIe" label="AppleColor Composite Monitor IIe" image="images/Apple/AppleColor Composite Monitor IIe.png">
        <setting ref="appleColorCompositeMonitorIIe.monitor" name="videoBrightness" label="Brightness" type="slider" options="-1.0,1.0"/>
        <setting ref="appleColorCompositeMonitorIIe.monitor" name="videoContrast" label="Contrast" type="slider" options="0.0,2.0,1.0"/>
        <setting ref="appleColorCompositeMonitorIIe.monitor" name="videoSaturation" label="Saturation" type="slider" options="0.0,2.0,1.0"/>
        <setting ref="appleColorCompositeMonitorIIe.monitor" name="videoHue" label="Hue" type="slider" options="-0.5,0.5,0.0"/>
        <setting ref="appleColorCompositeMonitorIIe.monitor" name="videoWhiteOnly" label="White Only" type="checkbox"/>
        <setting ref="appleColorCompositeMonitorIIe.monitor" name="videoHorizontalCenter" label="Horizontal Center" type="slider" options="-0.1,0.1"/>
        <setting ref="appleColorCompositeMonitorIIe.monitor" name="videoVerticalCenter" label="Vertical Center" type="slider" options="-0.1,0.1"/>
        <setting ref="appleColorCompositeMonitorIIe.monitor" name="videoVerticalSize" label="Vertical Size" type="slider" options="0.85,1.25"/>
    </device>
    <connector id="appleColorCompositeMonitorIIe.connector" type="Composite Video Port">
        <inlet ref="appleColorCompositeMonitorIIe.monitor" property="controlBus" outletRef="controlBus"/>
    </connector>
    <component id="appleColorCompositeMonitorIIe.monitor" class="Monitor">
        <property name="device" ref="appleColorCompositeMonitorIIe"/>
        <property name="controlBus" ref=""/>
        <property name="videoDecoder" value="Composite Y'UV"/>
        <property name="videoBrightness" value="0"/>
        <property name="videoContrast" value="1"/>
        <property name="videoSaturation" value="1"/>
        <property name="videoHue" value="0"/>
        <property name="videoWhiteOnly" value="0"/>
        <property name="videoHorizontalCenter" value="0"/>
        <property name="videoHorizontalSize" value="1.05"/>
        <property name="videoVerticalCenter" value="0"/>
        <property name="videoVerticalSize" value="1.05"/>
        <property name="videoBandwidth" value="4500000"/>
        <property name="videoLumaBandwidth" value="2000000"/>
        <property name="videoChromaBandwidth" value="600000"/>
        <property name="displayBarrel" value="0.05"/>
        <property name="displayScanlineLevel" value="0.05"/>
        <property name="displayShadowMaskLevel" value="0.05"/>
        <property name="displayShadowMaskDotPitch" value="0.5"/>
        <property name="displayShadowMask" value="Triad"/>
        <property name="displayPersistence" value="0"/>
        <property name="displayCenterLighting" value="1"/>
        <property name="displayLuminanceGain" value="1"/>
    </component>
    
</edl>

=== salfter/openemulator/templates/Apple-1/Briel Replica-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTDs/edl-1.0.dtd">
<edl version="1.0" generator="OpenEmulator" framework="700" label="Replica-1" image="images/Briel/Replica-1.png" description="The Replica-1 (www.brielcomputers.com) is a functional clone of the Apple-1 computer. It features a WDC 65C02 microprocessor, 32 kiB RAM (at $0000-$7FFF), and 8 kiB bytes ROM (BASIC at $E000-$EFFF, Krusader at $F000-$FEFF, Monitor at $FF00-$FFFF).">
    
    <device id="replica1" label="Replica-1" image="images/Briel/Replica-1.png">
        <setting ref="replica1.io" name="terminalSpeed" label="Terminal Speed" type="select" options="Standard,Enhanced"/>
        <setting ref="replica1.io" name="keyboardType" label="Keyboard" type="select" options="Standard,Full ASCII"/>
    </device>
    <port id="replica1.videoPort" ref="" type="Composite Video Port" group="peripherals" label="Video Port" image="images/Connectors/RCA Female.png">
        <inlet ref="replica1.terminal" property="monitorDevice" outletRef=""/>
        <inlet ref="replica1.terminal" property="monitor" outletRef="monitor"/>
    </port>
    <port id="replica1.slot1" ref="" type="Apple-1 Expansion Port" group="expansions" label="Expansion Port" image="images/Connectors/Edge44.png"/>
    <port id="replica1.slot2" ref="" type="Apple-1 Expansion Port" group="expansions" label="Expansion Port" image="images/Connectors/Edge44.png"/>
    <component id="replica1.controlBus" class="ControlBus">
        <property name="device" ref="replica1"/>
        <property name="audio" ref="audio"/>
        <!-- Clock frequency: 14318180 Hz * 61 / 910 -->
        <property name="clockFrequency" value="959790.088"/>
        <property name="cpuClockMultiplier" value="1"/>
        <property name="cpu" ref="replica1.cpu"/>
        <property name="resetOnPowerOn" value="1"/>
        <property name="powerState" value="0"/>
        <property name="resetCount" value="0"/>
        <property name="irqCount" value="0"/>
        <property name="nmiCount" value="0"/>
    </component>
    <component id="replica1.memoryBus" class="AddressDecoder">
        <property name="addressSize" value="16"/>
        <property name="blockSize" value="8"/>
        <property name="floatingBus" ref="replica1.floatingBus"/>
        <property name="refRAM" ref="replica1.ram"/>
        <property name="mapRAM" value="0x0000-0x7fff"/>
        <property name="refIO" ref="replica1.ioMemory"/>
        <property name="mapIO" value="0xd000-0xdfff"/>
        <property name="refROM" ref="replica1.rom"/>
        <property name="mapROM" value="0xe000-0xffff"/>
    </component>
    <component id="replica1.cpu" class="W65C02S">
        <property name="a" value="0x0"/>
        <property name="x" value="0x0"/>
        <property name="y" value="0x0"/>
        <property name="s" value="0x0"/>
        <property name="p" value="0x0"/>
        <property name="pc" value="0xff00"/>
        <property name="memoryBus" ref="replica1.memoryBus"/>
        <property name="controlBus" ref="replica1.controlBus"/>
    </component>
    <component id="replica1.floatingBus" class="FloatingBus">
        <property name="mode" value="ground"/>
    </component>
    <component id="replica1.ram" class="RAM">
        <property name="controlBus" ref="replica1.controlBus"/>
        <property name="image" data="${packagePath}/${id}.bin"/>
        <property name="size" value="0x8000"/>
    </component>
    <component id="replica1.ioMemory" class="AddressDecoder">
        <property name="addressSize" value="5"/>
        <property name="blockSize" value="4"/>
        <property name="floatingBus" ref="replica1.floatingBus"/>
        <property name="refPIA" ref="replica1.pia"/>
        <property name="mapPIA" value="0x10-0x1f"/>
    </component>
    <component id="replica1.pia" class="MC6821">
        <property name="controlBus" ref="replica1.controlBus"/>
        <property name="portA" ref="replica1.io"/>
        <property name="controlA" value="0x0"/>
        <property name="directionA" value="0x0"/>
        <property name="dataA" value="0x0"/>
        <property name="ca1" value="0"/>
        <property name="ca2" value="0"/>
        <property name="controlBusA" ref=""/>
        <property name="portB" ref="replica1.io"/>
        <property name="controlB" value="0x0"/>
        <property name="directionB" value="0x0"/>
        <property name="dataB" value="0x0"/>
        <property name="cb1" value="0"/>
        <property name="cb2" value="0"/>
        <property name="controlBusB" ref=""/>
    </component>
    <component id="replica1.io" class="Apple1IO">
        <property name="pia" ref="replica1.pia"/>
        <property name="terminal" ref="replica1.terminal"/>
        <property name="terminalSpeed" value="Enhanced"/>
        <property name="keyboardType" value="Standard"/>
    </component>
    <component id="replica1.terminalRAM" class="RAM">
        <property name="controlBus" ref="replica1.controlBus"/>
        <property name="image" data="${packagePath}/${id}.bin"/>
        <property name="size" value="1024"/>
        <property name="powerOnPattern" value="0x20"/>
    </component>
    <component id="replica1.terminal" class="Apple1Terminal">
        <property name="device" ref="replica1"/>
        <property name="vram" ref="replica1.terminalRAM"/>
        <property name="controlBus" ref="replica1.controlBus"/>
        <property name="monitorDevice" ref=""/>
        <property name="monitor" ref=""/>
        <property name="font" data="${resourcePath}/roms/Signetics/Signetics 2513 Video ROM.bin"/>
        <property name="cursorX" value="0"/>
        <property name="cursorY" value="0"/>
    </component>
    <component id="replica1.rom" class="ROM">
        <property name="image" data="${resourcePath}/roms/Briel/Replica-1 65C02 ROM.bin"/>
    </component>
    
</edl>

=== salfter/openemulator/library/Apple II/Apple Silentype Interface Card.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" generator="OpenEmulator" framework="736" label="Apple Silentype Interface Card" image="images/Apple/Apple Synch Printer Interface Card.png" description="The Apple Silentype Printer Interface Card connects an Apple Silentype printer to an Apple II computer. It is usually installed in slot 1.">
    
    <device id="appleSilentypeInterfaceCard" label="Apple Silentype Interface Card" image="images/Apple/Apple Synch Printer Interface Card.png">
    </device>
    <connector id="appleSilentypeInterfaceCard.connector" type="Apple II Slot">
        <inlet ref="appleSilentypeInterfaceCard.memory" property="memoryBus" outletRef="memoryBus"/>
        <inlet ref="appleSilentypeInterfaceCard.memoryCF00" property="floatingBus" outletRef="floatingBus"/>
        <inlet ref="appleSilentypeInterfaceCard.disableC800" property="memoryBus" outletRef="memoryBus"/>
    </connector>
    <port id="appleSilentypeInterfaceCard.port" ref="" type="Apple Silentype Port" group="peripherals" label="Silentype Port" image="images/Connectors/DE9 Female.png"/>
    <component id="appleSilentypeInterfaceCard.io" class="FloatingBus">
    </component>
    <component id="appleSilentypeInterfaceCard.memory" class="AppleIISlotController">
        <property name="memory" ref="appleSilentypeInterfaceCard.rom"/>
        <property name="en" value="0"/>
        <property name="memoryBus" ref=""/>
        <property name="refROM" ref="appleSilentypeInterfaceCard.rom"/>
        <property name="mapROM" value="0xc800-0xceff"/>
        <property name="refCF00" ref="appleSilentypeInterfaceCard.memoryCF00"/>
        <property name="mapCF00" value="0xcf00-0xcfff"/>
    </component>
    <component id="appleSilentypeInterfaceCard.memoryCF00" class="AddressDecoder">
        <property name="size" value="0x100"/>
        <property name="blockSize" value="0x1"/>
        <property name="floatingBus" ref=""/>
        <property name="refDisableC800" ref="appleSilentypeInterfaceCard.disableC800"/>
        <property name="mapDisableC800" value="0xff"/>
    </component>
    <component id="appleSilentypeInterfaceCard.rom" class="ROM">
        <property name="memoryImage" data="${resourcePath}/roms/Apple/341-0039-00.bin"/>
    </component>
    <component id="appleSilentypeInterfaceCard.disableC800" class="AppleIIDisableC800">
        <property name="memory" ref="appleSilentypeInterfaceCard.memory"/>
        <property name="memoryBus" ref=""/>
    </component>
    
</edl>

=== salfter/openemulator/library/Apple II/Videx UltraTerm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" label="Videx UltraTerm" image="images/Videx/Videx UltraTerm.png" description="The Videx UltraTerm is an extended column video card for Apple II computers. It can be installed in slots 0 to 7.">
    
    <device id="videxUltraTerm" label="Videx UltraTerm" image="images/Videx/Videx UltraTerm.png">
    </device>
    <connector id="videxUltraTerm.connector" type="Apple II Slot">
        <inlet ref="videxUltraTerm.memory" property="memoryBus" outletRef="memoryBus"/>
    </connector>
    <component id="videxUltraTerm.io" class="FloatingBus">
    </component>
    <component id="videxUltraTerm.memory" class="AppleIISlotMemory">
        <property name="memoryBus" ref=""/>
        <property name="memory" ref="videxUltraTerm.rom"/>
        <property name="en" value="0"/>
    </component>
    <component id="videxUltraTerm.rom" class="ROM">
        <property name="memoryImage" data="${resourcePath}/roms/Videx/Videx UltraTerm ROM.bin"/>
    </component>
    
</edl>

=== salfter/openemulator/library/Terminals/Terminal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" label="Terminal" image="Terminal.png">

<device id="terminal" label="Terminal" image="Terminal.png" />
<connector id="terminal.connector" ref="" type="RS232" label="Connector" image="Serial Port Connector.png" />
<component id="terminal.io" class="Terminal">
    <property name="host" ref="hostEmulationController" />
    <property name="charset" ref="terminal.charset" />
    <property name="width" value="24" />
    <property name="height" value="40" />
</component>
<component id="terminal.charset" class="CharsetLoader">
    <property name="format" value="Signetics" />
    <property name="image" src="${resourcePath}/roms/Signetics/Signetics 2513 Video ROM.bin" />
</component>

</edl>

=== salfter/openemulator/library/Monitors/Apple Monitor IIc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" generator="OpenEmulator" build="736" label="Apple Monitor IIc" image="images/Apple/Apple Monitor IIc.png" description="The Apple Monitor IIc is a CRT-based green monochrome 9-inch monitor manufactured by Apple Computer for the Apple IIc personal computer.">
    
    <device id="appleMonitorIIc" label="Apple Monitor IIc" image="images/Apple/Apple Monitor IIc.png">
        <setting ref="appleMonitorIIc.monitor" name="videoBrightness" label="Brightness" type="slider" options="-1.0,1.0"/>
        <setting ref="appleMonitorIIc.monitor" name="videoContrast" label="Contrast" type="slider" options="0.0,1.0"/>
        <setting ref="appleMonitorIIc.monitor" name="videoVerticalCenter" label="Vertical Center" type="slider" options="-0.1,0.1"/>
        <setting ref="appleMonitorIIc.monitor" name="videoVerticalSize" label="Vertical Size" type="slider" options="0.85,1.25"/>
    </device>
    <connector id="appleMonitorIIc.connector" type="Composite Video Port">
        <inlet ref="appleMonitorIIc.monitor" property="controlBus" outletRef="controlBus"/>
    </connector>
    <component id="appleMonitorIIc.monitor" class="Monitor">
        <property name="device" ref="appleMonitorIIc"/>
        <property name="controlBus" ref=""/>
        <property name="videoDecoder" value="Monochrome"/>
        <property name="videoBrightness" value="0.15"/>
        <property name="videoContrast" value="0.8"/>
        <property name="videoSaturation" value="1.45"/>
        <property name="videoHue" value="0.27"/>
        <property name="videoHorizontalCenter" value="0"/>
        <property name="videoHorizontalSize" value="1.05"/>
        <property name="videoVerticalCenter" value="0"/>
        <property name="videoVerticalSize" value="1.05"/>
        <property name="videoBandwidth" value="6000000"/>
        <property name="displayBarrel" value="0.1"/>
        <property name="displayScanlineLevel" value="0.5"/>
        <property name="displayCenterLighting" value="0.5"/>
        <property name="displayLuminanceGain" value="1.5"/>
    </component>
    
</edl>
