=== salfter/openemulator/libemulation/edl-1.0.dtd
<!--
   Emulation Description Language version 1.0 DTD

   For further information, see: http://www.openemulator.org

   Copyright (c) 2010-2011 Marc S. Ressl,
   All Rights Reserved. 

   This DTD module is identified by the PUBLIC and SYSTEM identifiers:

   PUBLIC "-//W3C//DTD EDL 1.0//EN"
   SYSTEM "http://www.openemulator.org/DTD/edl-1.dtd"

   $Revision: 0.8 $
   $Date: 2011/09/10 17:00:00-0300 $
-->

<!ELEMENT edl (device*|port*|connector*|component*)>
<!ATTLIST edl version CDATA "1.0">
<!ATTLIST edl generator CDATA #REQUIRED>
<!ATTLIST edl framework CDATA #REQUIRED>
<!ATTLIST edl label CDATA #IMPLIED>
<!ATTLIST edl image CDATA #IMPLIED>
<!ATTLIST edl description CDATA #IMPLIED>

<!ELEMENT device (setting*)>
<!ATTLIST device id ID #REQUIRED>
<!ATTLIST device label CDATA #REQUIRED>
<!ATTLIST device image CDATA #IMPLIED>

<!ELEMENT setting EMPTY>
<!ATTLIST setting ref IDREF #REQUIRED>
<!ATTLIST setting name CDATA #REQUIRED>
<!ATTLIST setting label CDATA #REQUIRED>
<!ATTLIST setting type CDATA #REQUIRED>
<!ATTLIST setting options CDATA #IMPLIED>

<!ELEMENT port (inlet*)>
<!ATTLIST port id ID #REQUIRED>
<!ATTLIST port ref CDATA #REQUIRED>
<!ATTLIST port type CDATA #REQUIRED>
<!ATTLIST port group CDATA #IMPLIED>
<!ATTLIST port label CDATA #REQUIRED>
<!ATTLIST port image ID #IMPLIED>

<!ELEMENT connector (inlet*)>
<!ATTLIST connector id ID #REQUIRED>
<!ATTLIST connector type CDATA #REQUIRED>

<!ELEMENT inlet EMPTY>
<!ATTLIST inlet ref IDREF #REQUIRED>
<!ATTLIST inlet property CDATA #REQUIRED>
<!ATTLIST inlet outletRef CDATA #REQUIRED>

<!ELEMENT component (property*)>
<!ATTLIST component id ID #REQUIRED>
<!ATTLIST component class CDATA #REQUIRED>

<!ELEMENT property (setting*)>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #IMPLIED>
<!ATTLIST property ref CDATA #IMPLIED>
<!ATTLIST property src CDATA #IMPLIED>

=== salfter/openemulator/library/Monitors/Apple Monitor III.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" generator="OpenEmulator" build="700" label="Apple Monitor III" image="images/Apple/Apple Monitor III.png" description="The Apple Monitor III is a CRT-based green monochrome 12-inch monitor manufactured by Apple Computer for the Apple III personal computer.">
    
    <device id="appleMonitorIII" label="Apple Monitor III" image="images/Apple/Apple Monitor III.png">
        <setting ref="appleMonitorIII.monitor" name="videoBrightness" label="Brightness" type="slider" options="-1.0,1.0"/>
        <setting ref="appleMonitorIII.monitor" name="videoContrast" label="Contrast" type="slider" options="0.0,1.0"/>
        <setting ref="appleMonitorIII.monitor" name="videoVerticalCenter" label="Vertical Center" type="slider" options="-0.1,0.1"/>
        <setting ref="appleMonitorIII.monitor" name="videoVerticalSize" label="Vertical Size" type="slider" options="0.8,1.2"/>
    </device>
    <connector id="appleMonitorIII.connector" type="Composite Video Port">
        <inlet ref="appleMonitorIII.monitor" property="controlBus" outletRef="controlBus"/>
    </connector>
    <component id="appleMonitorIII.monitor" class="Monitor">
        <property name="device" ref="appleMonitorIII"/>
        <property name="controlBus" ref="controlBus"/>
        <property name="videoDecoder" value="Monochrome"/>
        <property name="videoBrightness" value="0.1"/>
        <property name="videoContrast" value="0.75"/>
        <property name="videoSaturation" value="1.4"/>
        <property name="videoHue" value="0.33"/>
        <property name="videoHorizontalCenter" value="0"/>
        <property name="videoHorizontalSize" value="1.0"/>
        <property name="videoVerticalCenter" value="0"/>
        <property name="videoVerticalSize" value="1.0"/>
        <property name="videoBandwidth" value="15000000.0"/>
        <property name="displayBarrel" value="0.1"/>
        <property name="displayScanlineAlpha" value="0.5"/>
        <property name="displayCenterLighting" value="0.5"/>
        <property name="displayPersistance" value="0.9"/>
    </component>
    
</edl>

=== salfter/openemulator/templates/Commodore 64/Commodore 64.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" label="Commodore 64" image="images/Commodore/Commodore 64.png" description="">
    
    <device id="c64" label="Commodore 64" image="images/Commodore/Commodore 64.png">
    </device>
    <port id="c64.video" ref="" type="Composite Video Port" group="peripherals" label="Video Port" image="images/Connectors/RCA Female.png">
    </port>
    <port id="c64.control1" ref="" type="Commodore Control Port" group="peripherals" label="Control Port 1" image="images/Connectors/DE9 Male.png">
    </port>
    <port id="c64.control2" ref="" type="Commodore Control Port" group="peripherals" label="Control Port 2" image="images/Connectors/DE9 Male.png">
    </port>
    <port id="c64.expansion" ref="" type="Commodore Expansion Port" group="peripherals" label="Expansion Port" image="images/Connectors/Edge44.png">
    </port>
    <port id="c64.serial" ref="" type="IEEE-488 Port" label="Serial Port" group="peripherals" image="images/Connectors/DIN45322.png">
    </port>
    <port id="c64.cassette" ref="" type="Commodore Datasette Port" group="peripherals" label="Datasette Port" image="images/Commodore/Commodore 64 Cassette Port.png">
    </port>
    <port id="c64.user" ref="" type="Commodore User Port" group="peripherals" label="User Port" image="images/Commodore/Commodore 64 User Port.png">
    </port>
    
</edl>

=== salfter/openemulator/hardware/Serial Port Controllers/Apple II Super Serial Card.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" label="Super Serial Card" image="images/Apple II/Apple II Super Serial Card.png">

<device id="ssc" label="Apple II Super Serial Card" image="images/Apple II/Apple II Super Serial Card.png">
    <setting ref="ssc.io" name="mode" type="select" options="Communications Mode,Printer Mode" label="Mode" />
    <setting ref="ssc.io" name="baudRate" type="select" options="50,75,110,135,150,300,600,1200,1800,2400,3600,4800,7200,9600,19200" label="Baud Rate" />
    <setting ref="ssc.io" name="dataBits" type="select" options="7,8" label="Data Bits" />
    <setting ref="ssc.io" name="stopBits" type="select" options="1,2" label="Stop Bits" />
    <setting ref="ssc.io" name="parity" type="select" options="None,Even,Odd" label="Parity" />
    <setting ref="ssc.io" name="autoLFAfterCR" type="checkbox" label="Auto LF after CR" />
    <setting ref="ssc.io" name="interrupts" type="checkbox" label="Enable interrupt" />
    <setting ref="ssc.io" name="charactersPerLine" type="select" options="40,72,80,132" label="Characters Per Line" />
    <setting ref="ssc.io" name="delayAfterCR" type="checkbox" label="Delay after CR" />
</device>
<connector id="ssc.connector" ref="" type="AppleIISlot" label="Apple II Super Serial Card" image="Apple II Super Serial Card.png" />
<port id="ssc.port" ref="" type="RS232" label="Serial Port" image="Serial Port.png">
    <inlet ref="ssc.io" property="port" outletRef="io" />
</port>
<component id="ssc.io" class="AppleIISuperSerialCard">
    <property name="port" ref="" />
    <property name="mode" value="0" />
    <property name="baudRate" value="9600" />
    <property name="dataBits" value="1" />
    <property name="stopBits" value="1" />
    <property name="parity" value="0" />
    <property name="autoLFAfterCR" value="0" />
    <property name="interrupts" value="0" />
    <property name="charactersPerLine" value="0" />
    <property name="delayAfterCR" value="0" />
</component>
<component id="ssc.memory" class="ROM">
    <property name="image" src="roms/Apple II/Apple II Super Serial Card ROM.bin" />
</component>

</edl>

=== salfter/openemulator/hardware/Monitors/Composite Monitor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" label="Composite Video Monitor" image="Composite Video Monitor.png" group="Monitors">

<device id="monitor" type="Peripheral" label="Composite Video Monitor" image="Composite Video Monitor.png">
    <setting ref="monitor.monitor" name="brightness" type="value" options="0.0,2.0" label="Brightness" />
    <setting ref="monitor.monitor" name="contrast" type="value" options="0.0,2.0" label="Contrast" />
    <setting ref="monitor.monitor" name="saturation" type="value" options="0.0,2.0" label="Saturation" />
    <setting ref="monitor.monitor" name="hue" type="value" options="0.0,2.0" label="Hue" />
</device>
<connector id="monitor.connector" label="Video Connector" image="Composite Video Connector.png" />
<component id="monitor.monitor" class="CompositeMonitor">
    <property name="compositeLumaCutoff" value="0.3" />
    <property name="compositeChromaCutoff" value="0.06" />
    <property name="compositeHue" value="0.06" />
    <property name="compositeBrightness" value="0.06" />
    <property name="compositeColorize" value="0" />
    <property name="compositeDecoderMatrix" value="standard" />
    <property name="screenBrightness" value="0.0" />
    <property name="screenContrast" value="1.0" />
    <property name="screenRedGain" value="1.0" />
    <property name="screenGreenGain" value="1.0" />
    <property name="screenBlueGain" value="1.0" />
    <property name="screenBarrel" value="0.05" />
    <property name="screenPersistance" value="0.0" />
    <property name="screenHorizCenter" value="0.5" />
    <property name="screenHorizSize" value="1.0" />
    <property name="screenVertCenter" value="0.5" />
    <property name="screenVertSize" value="1.0" />
</component>

</edl>

=== salfter/openemulator/library/Apple-1/R&D CFFA1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE EDL PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" creator="OpenEmulator" framework="787" label="RD CFFA1" image="images/R&amp;D/R&amp;D CFFA1.png" description="The CFFA1 interface card (www.dreher.net) accesses block disk images on Apple-1 computers. It also provides 32kiB of RAM at $1000-$8FFF. To start the file manager, enter 9000R in the monitor.">
    
    <device id="rdCFFA1" label="R&amp;D CFFA1" image="images/R&amp;D/R&amp;D CFFA1.png">
        <setting ref="rdCFFA1.ataDevice" name="forceWriteProtected" label="Force Write Protected" type="checkbox"/>
    </device>
    <connector id="rdCFFA1.connector" type="Apple-1 Expansion Port">
        <inlet ref="rdCFFA1.addressMapper" property="addressDecoder" outletRef="memoryBus"/>
        <inlet ref="rdCFFA1.ram" property="controlBus" outletRef="controlBus"/>
    </connector>
    <component id="rdCFFA1.addressMapper" class="AddressMapper">
        <property name="addressDecoder" ref=""/>
        <property name="mapRAM" value="0x1000-0x8fff"/>
        <property name="refRAM" ref="rdCFFA1.ram"/>
        <property name="mapROM" value="0x9000-0xaeff"/>
        <property name="refROM" ref="rdCFFA1.rom"/>
        <property name="mapIO" value="0xaf00-0xafff"/>
        <property name="refIO" ref="rdCFFA1.memoryAF00"/>
        <property name="sel" value="RAM,ROM,IO"/>
    </component>
    <component id="rdCFFA1.ram" class="RAM">
        <property name="memoryImage" data="${packagePath}/${id}.bin"/>
        <property name="size" value="0x8000"/>
        <property name="controlBus" ref=""/>
    </component>
    <component id="rdCFFA1.rom" class="ROM">
        <property name="memoryImage" data="${resourcePath}/roms/R&amp;D/CFFA1V1.0.bin"/>
    </component>
    <component id="rdCFFA1.memoryAF00" class="AddressDecoder">
        <property name="size" value="0x100"/>
        <property name="blockSize" value="0x20"/>
        <property name="floatingBus" ref="rdCFFA1.rom"/>
        <property name="mapIO" value="0xe0-0xff"/>
        <property name="refIO" ref="rdCFFA1.io"/>
    </component>
    <component id="rdCFFA1.io" class="RDCFFA">
        <property name="ataController" ref="rdCFFA1.ataController"/>
    </component>
    <component id="rdCFFA1.ataController" class="ATAController">
        <property name="drive1" ref="rdCFFA1.ataDevice"/>
    </component>
    <component id="rdCFFA1.ataDevice" class="ATADevice">
        <property name="device" ref="rdCFFA1"/>
        <property name="diskImage" value=""/>
        <property name="forceWriteProtected" value="0"/>
        <property name="maxSize" value="65535"/>
    </component>
    
</edl>

=== salfter/openemulator/library/Apple II/Apple Graphics Tablet Interface Card.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" label="Apple Grahpics Tablet Interface Card" image="images/Apple/Apple Graphics Tablet Interface Card.png" description="The Apple Graphics Tablet Interface Card is used for connecting an Apple Graphics Tablet to an Apple II computer. It is usually installed in slot 5.">

<device id="appleGTIC" label="Apple Graphics Tablet Interface Card" image="images/Apple/Apple Graphics Tablet Interface Card.png" group="expansions" />
<connector id="appleGTIC.connector" ref="" type="Apple II Slot" label="Connector" >
    <inlet ref="appleGTIC.io" property="mmu" outletRef="mmu" />
</connector>
<port id="appleGTIC.port" ref="" type="Apple Graphics Tablet" label="Graphics Tablet Port" image="images/Connectors/Header1x6 Male.png">
</port>
<component id="appleGTIC.io" class="AppleLanguageCard">
    <property name="mmu" ref="" />
</component>
<component id="appleGTIC.memoryOffset" class="MemoryOffset">
    <property name="component" ref="languageCard.memory" />
</component>

</edl>

=== salfter/openemulator/library/Apple-1/RD CFFA1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" generator="OpenEmulator" build="700" label="RD CFFA1" image="images/RD/RD CFFA1.png" description="The CFFA1 interface card (www.dreher.net) is used for accessing CompactFlash devices on an Apple-1 computer. It also provides 32kiB of RAM at $1000-$8FFF. To start the file manager, enter 9000R in the monitor.">
    
    <device id="rdCFFA1" label="RD CFFA1" image="images/RD/RD CFFA1.png">
    </device>
    <connector id="rdCFFA1.connector" type="Apple-1 Expansion Port">
        <inlet ref="rdCFFA1.ram" property="controlBus" outletRef="controlBus"/>
    </connector>
    <component id="rdCFFA1.ram" class="RAM">
        <property name="controlBus" ref=""/>
        <property name="image" data="${packagePath}/${id}.bin"/>
        <property name="size" value="0x8000"/>
    </component>
    <component id="rdCFFA1.rom" class="ROM">
        <property name="image" data="${resourcePath}/roms/RD/CFFA1V1.0.bin"/>
    </component>
    
</edl>

=== salfter/openemulator/templates/Apple-1/Apple-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTDs/edl-1.0.dtd">
<edl version="1.0" generator="OpenEmulator" framework="700" label="Apple-1" image="images/Apple/Apple-1.png" description="The Apple-1 is an early personal computer, and the first in combining a microprocessor with a connection for a keyboard and a monitor. It features a MOS 6502 microprocessor, 8 kiB RAM (at $0000-$0FFF and $E000-$EFFF), and 256 bytes ROM (at $FF00-$FFFF).">
    
    <device id="apple1" label="Apple-1" image="images/Apple/Apple-1.png">
        <setting ref="apple1.io" name="terminalSpeed" label="Terminal Speed" type="select" options="Standard,Enhanced"/>
        <setting ref="apple1.io" name="keyboardType" label="Keyboard" type="select" options="Standard,Full ASCII"/>
    </device>
    <port id="apple1.videoPort" ref="appleMonitorIII.connector" type="Composite Video Port" group="peripherals" label="Video Port" image="images/Connectors/RCA Female.png">
        <inlet ref="apple1.terminal" property="monitorDevice" outletRef=""/>
        <inlet ref="apple1.terminal" property="monitor" outletRef="monitor"/>
    </port>
    <port id="apple1.slot1" ref="" type="Apple-1 Expansion Port" group="expansions" label="Expansion Port" image="images/Connectors/Edge44.png"/>
    <port id="apple1.slot2" ref="" type="Apple-1 Expansion Port" group="expansions" label="Expansion Port" image="images/Connectors/Edge44.png"/>
    <component id="apple1.controlBus" class="ControlBus">
        <property name="device" ref="apple1"/>
        <property name="audio" ref="audio"/>
        <!-- Clock frequency: 14318180 Hz * 61 / 910 -->
        <property name="clockFrequency" value="959790.088"/>
        <property name="cpuClockMultiplier" value="1"/>
        <property name="cpu" ref="apple1.cpu"/>
        <property name="powerState" value="S0"/>
        <property name="resetOnPowerOn" value="1"/>
        <property name="resetCount" value="0"/>
        <property name="irqCount" value="0"/>
        <property name="nmiCount" value="0"/>
    </component>
    <component id="apple1.memoryBus" class="AddressDecoder">
        <property name="addressSize" value="16"/>
        <property name="blockSize" value="8"/>
        <property name="floatingBus" ref="apple1.floatingBus"/>
    </component>
    <component id="apple1.mmu" class="MMU">
        <property name="addressDecoder" ref="apple1.memoryBus"/>
        <property name="refRAM1" ref="apple1.ram1"/>
        <property name="mapRAM1" value="0x0000-0x0fff"/>
        <property name="refIO" ref="apple1.ioMemory"/>
        <property name="mapIO" value="0xd000-0xdfff"/>
        <property name="refRAM2" ref="apple1.ram2"/>
        <property name="mapRAM2" value="0xe000-0xefff"/>
        <property name="refROM" ref="apple1.rom"/>
        <property name="mapROM" value="0xf000-0xffff"/>
    </component>
    <component id="apple1.cpu" class="MOS6502">
        <property name="a" value="0x0"/>
        <property name="x" value="0x0"/>
        <property name="y" value="0x0"/>
        <property name="s" value="0x0"/>
        <property name="p" value="0x0"/>
        <property name="pc" value="0xff00"/>
        <property name="controlBus" ref="apple1.controlBus"/>
        <property name="memoryBus" ref="apple1.memoryBus"/>
    </component>
    <component id="apple1.floatingBus" class="FloatingBus">
        <property name="mode" value="ground"/>
    </component>
    <component id="apple1.ram1" class="RAM">
        <property name="controlBus" ref="apple1.controlBus"/>
        <property name="image" data="${packagePath}/${id}.bin"/>
        <property name="size" value="0x1000"/>
    </component>
    <component id="apple1.ioMemory" class="AddressDecoder">
        <property name="addressSize" value="5"/>
        <property name="blockSize" value="4"/>
        <property name="floatingBus" ref="apple1.floatingBus"/>
        <property name="refPIA" ref="apple1.pia"/>
        <property name="mapPIA" value="0x10-0x1f"/>
    </component>
    <component id="apple1.pia" class="MC6821">
        <property name="controlBus" ref="apple1.controlBus"/>
        <property name="portA" ref="apple1.io"/>
        <property name="controlA" value="0x0"/>
        <property name="directionA" value="0x0"/>
        <property name="dataA" value="0x0"/>
        <property name="ca1" value="0"/>
        <property name="ca2" value="0"/>
        <property name="controlBusA" ref=""/>
        <property name="portB" ref="apple1.io"/>
        <property name="controlB" value="0x0"/>
        <property name="directionB" value="0x0"/>
        <property name="dataB" value="0x0"/>
        <property name="cb1" value="0"/>
        <property name="cb2" value="0"/>
        <property name="controlBusB" ref=""/>
    </component>
    <component id="apple1.io" class="Apple1IO">
        <property name="terminalSpeed" value="Standard"/>
        <property name="keyboardType" value="Standard"/>
        <property name="pia" ref="apple1.pia"/>
        <property name="terminal" ref="apple1.terminal"/>
    </component>
    <component id="apple1.terminalRAM" class="RAM">
        <property name="controlBus" ref="apple1.controlBus"/>
        <property name="image" data="${packagePath}/${id}.bin"/>
        <property name="size" value="1024"/>
        <property name="powerOnPattern" value="0x20"/>
    </component>
    <component id="apple1.terminal" class="Apple1Terminal">
        <property name="cursorX" value="0"/>
        <property name="cursorY" value="0"/>
        <property name="device" ref="apple1"/>
        <property name="vram" ref="apple1.terminalRAM"/>
        <property name="controlBus" ref="apple1.controlBus"/>
        <property name="monitorDevice" ref="appleMonitorIII"/>
        <property name="monitor" ref="appleMonitorIII.monitor"/>
        <property name="font" data="${resourcePath}/roms/Signetics/Signetics 2513 Video ROM.bin"/>
    </component>
    <component id="apple1.ram2" class="RAM">
        <property name="controlBus" ref="apple1.controlBus"/>
        <property name="image" data="${packagePath}/${id}.bin"/>
        <property name="size" value="0x1000"/>
    </component>
    <component id="apple1.rom" class="ROM">
        <property name="image" data="${resourcePath}/roms/Apple/Apple-1 Monitor ROM.bin"/>
    </component>
    
    <device id="appleMonitorIII" label="Apple Monitor III" image="images/Apple/Apple Monitor III.png">
        <setting ref="appleMonitorIII.monitor" name="videoBrightness" label="Brightness" type="slider" options="-1.0,1.0"/>
        <setting ref="appleMonitorIII.monitor" name="videoContrast" label="Contrast" type="slider" options="0.0,1.0"/>
        <setting ref="appleMonitorIII.monitor" name="videoVerticalCenter" label="Vertical Center" type="slider" options="-0.1,0.1"/>
        <setting ref="appleMonitorIII.monitor" name="videoVerticalSize" label="Vertical Size" type="slider" options="0.85,1.25"/>
    </device>
    <connector id="appleMonitorIII.connector" type="Composite Video Port">
        <inlet ref="appleMonitorIII.monitor" property="controlBus" outletRef="controlBus"/>
    </connector>
    <component id="appleMonitorIII.monitor" class="Monitor">
        <property name="device" ref="appleMonitorIII"/>
        <property name="controlBus" ref="apple1.controlBus"/>
        <property name="videoDecoder" value="Monochrome"/>
        <property name="videoBrightness" value="0.15"/>
        <property name="videoContrast" value="0.8"/>
        <property name="videoSaturation" value="1.45"/>
        <property name="videoHue" value="0.27"/>
        <property name="videoHorizontalCenter" value="0"/>
        <property name="videoHorizontalSize" value="1.05"/>
        <property name="videoVerticalCenter" value="0"/>
        <property name="videoVerticalSize" value="1.05"/>
        <property name="videoBandwidth" value="4500000"/>
        <property name="displayBarrel" value="0.1"/>
        <property name="displayScanlineLevel" value="0.5"/>
        <property name="displayCenterLighting" value="0.5"/>
        <property name="displayPersistence" value="0.4"/>
        <property name="displayLuminanceGain" value="1.5"/>
    </component>
    
</edl>
