=== salfter/openemulator/libemulation/edl-1.0.dtd
<!--
   Emulation Description Language version 1.0 DTD

   For further information, see: http://www.openemulator.org

   Copyright (c) 2010-2011 Marc S. Ressl,
   All Rights Reserved. 

   This DTD module is identified by the PUBLIC and SYSTEM identifiers:

   PUBLIC "-//W3C//DTD EDL 1.0//EN"
   SYSTEM "http://www.openemulator.org/DTD/edl-1.dtd"

   $Revision: 0.8 $
   $Date: 2011/09/10 17:00:00-0300 $
-->

<!ELEMENT edl (device*|port*|connector*|component*)>
<!ATTLIST edl version CDATA "1.0">
<!ATTLIST edl generator CDATA #REQUIRED>
<!ATTLIST edl framework CDATA #REQUIRED>
<!ATTLIST edl label CDATA #IMPLIED>
<!ATTLIST edl image CDATA #IMPLIED>
<!ATTLIST edl description CDATA #IMPLIED>

<!ELEMENT device (setting*)>
<!ATTLIST device id ID #REQUIRED>
<!ATTLIST device label CDATA #REQUIRED>
<!ATTLIST device image CDATA #IMPLIED>

<!ELEMENT setting EMPTY>
<!ATTLIST setting ref IDREF #REQUIRED>
<!ATTLIST setting name CDATA #REQUIRED>
<!ATTLIST setting label CDATA #REQUIRED>
<!ATTLIST setting type CDATA #REQUIRED>
<!ATTLIST setting options CDATA #IMPLIED>

<!ELEMENT port (inlet*)>
<!ATTLIST port id ID #REQUIRED>
<!ATTLIST port ref CDATA #REQUIRED>
<!ATTLIST port type CDATA #REQUIRED>
<!ATTLIST port group CDATA #IMPLIED>
<!ATTLIST port label CDATA #REQUIRED>
<!ATTLIST port image ID #IMPLIED>

<!ELEMENT connector (inlet*)>
<!ATTLIST connector id ID #REQUIRED>
<!ATTLIST connector type CDATA #REQUIRED>

<!ELEMENT inlet EMPTY>
<!ATTLIST inlet ref IDREF #REQUIRED>
<!ATTLIST inlet property CDATA #REQUIRED>
<!ATTLIST inlet outletRef CDATA #REQUIRED>

<!ELEMENT component (property*)>
<!ATTLIST component id ID #REQUIRED>
<!ATTLIST component class CDATA #REQUIRED>

<!ELEMENT property (setting*)>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #IMPLIED>
<!ATTLIST property ref CDATA #IMPLIED>
<!ATTLIST property src CDATA #IMPLIED>

=== salfter/openemulator/hardware/Disk Drives/Apple Disk II Drive.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" label="Disk II Drive 1" image="Apple Disk II Drive.png">

<device id="diskII" label="Apple Disk II" image="images/apple2/Apple Disk II Drive.png" group="peripherals">
	<setting ref="diskII.drive" name="lock" type="checkbox" label="Lock" />
</device>
<connector id="diskII.connector" ref="" type="AppleIIDisk" label="Apple Disk II Slot Connector" />
<component id="diskII.drive" class="AppleDiskII">
    <property name="image" value="/Users/mressl/test2.dsk" />
    <property name="lock" value="0" />
    <property name="rpm" value="300.0" />
    <property name="rpmVariance" value="1.0" />
    <property name="soundSpin" src="sounds/Apple Disk II Spin.wav" />
    <property name="soundArm" src="sounds/Apple Disk II Arm.wav" />
    <property name="soundStop" src="sounds/Apple Disk II Stop.wav" />
    <property name="soundShake" src="sounds/Apple Disk II Shake.wav" />
</component>

</edl>

=== salfter/openemulator/library/Apple II/Disk Drive Controllers/Apple Game Paddles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" label="Apple Joystick" image="Apple II Game Paddles.png">

<device id="joystick" label="Game Paddles" image="Apple II Game Paddles.png" />
    <setting ref="mousePaddles.port" name="source" type="select" options="Mouse,Joystick" label="Source" />
    <setting ref="mousePaddles.port" name="invertAxis" type="checkbox" label="Invert axis" />
</device>
<connector id="joystick.connector" ref="" type="AppleIIGame" label="Apple II Game Paddles" image="Apple II Game Paddles.png" />
<component id="joystick.port" class="AppleIIGamePaddles">
    <property name="host" ref="host" />
    <property name="invertAxis" value="0" />
</component>

</edl>

=== salfter/openemulator/templates/Apple Macintosh/Macintosh 128K.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" label="Macintosh 128K" image="images/Apple/Apple Macintosh.png" description="">

<device id="appleMac128" label="Macintosh 128K" image="images/Apple/Apple Macintosh.png" group="system">
</device>
<port id="appleMac128.disk" ref="" type="Apple Disk Drive" label="Disk Drive Port" image="images/Connectors/DB19 Female.png">
</port>
<port id="appleMac128.serial" ref="" type="RS-422" label="Printer Port" image="images/Connectors/DE9 Female.png">
</port>
<port id="appleMac128.serial" ref="" type="RS-422" label="Serial Port" image="images/Connectors/DE9 Female.png">
</port>
<component id="appleMac128.monitor" class="Monitor">
    <property name="device" ref="appleMac128" />
    <property name="dummy" value="${resourcePath}/images/mac.png" />
    <property name="audio" ref="audio" />
</component>
<component id="appleMac128.disk" class="AppleDiskII">
    <property name="device" ref="appleMac128" />
    <property name="image" value="" />
    <property name="forceWriteProtected" value="0" />
</component>

</edl>

=== salfter/openemulator/library/Apple II/Apple Monitor III.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" label="Apple Monitor III" image="images/Apple/Apple Monitor III.png" description="The Apple Monitor III is a CRT-based green monochrome 12-inch monitor manufactured by Apple Computer for the Apple III personal computer.">

<device id="appleMonitorIII" label="Apple Monitor III" image="images/Apple/Apple Monitor III.png" group="peripherals">
    <setting ref="appleMonitorIII.monitor" name="videoBrightness" label="Brightness" type="slider" options="-1.0,1.0"/>
    <setting ref="appleMonitorIII.monitor" name="videoContrast" label="Contrast" type="slider" options="0.0,2.0,1.0"/>
    <setting ref="appleMonitorIII.monitor" name="videoSaturation" label="Saturation" type="slider" options="0.0,2.0,1.0"/>
    <setting ref="appleMonitorIII.monitor" name="videoHue" label="Hue" type="slider" options="-0.5,0.5,0.0"/>
    <setting ref="appleMonitorIII.monitor" name="videoHorizontalCenter" label="Horizontal Center" type="slider" options="-0.1,0.1"/>
    <setting ref="appleMonitorIII.monitor" name="videoHorizontalSize" label="Horizontal Size" type="slider" options="0.9,1.3"/>
    <setting ref="appleMonitorIII.monitor" name="videoVerticalCenter" label="Vertical Center" type="slider" options="-0.1,0.1"/>
    <setting ref="appleMonitorIII.monitor" name="videoVerticalSize" label="Vertical Size" type="slider" options="0.9,1.3"/>
</device>
<connector id="appleMonitorIII.connector" type="Composite Video"/>
<component id="appleMonitorIII.monitor" class="Monitor">
    <property name="device" ref="appleMonitorIII"/>
    <property name="videoDecoder" value="NTSC Y'UV"/>
    <property name="videoBandwidth" value="0.28"/>
    <property name="videoBrightness" value="0"/>
    <property name="videoContrast" value="1"/>
    <property name="videoSaturation" value="1"/>
    <property name="videoHue" value="0"/>
    <property name="videoHorizontalCenter" value="0"/>
    <property name="videoHorizontalSize" value="1.1"/>
    <property name="videoVerticalCenter" value="0"/>
    <property name="videoVerticalSize" value="1.1"/>
    <property name="displayBarrel" value="0.05"/>
    <property name="displayScanlineAlpha" value="0.05"/>
    <property name="displayCenterLighting" value="1"/>
    <property name="displayShadowMaskAlpha" value="0.05"/>
    <property name="displayShadowMaskDotPitch" value="0.5"/>
    <property name="displayShadowMask" value="Triad"/>
    <property name="compositeBlackLevel" value="0"/>
    <property name="compositeWhiteLevel" value="1"/>
    <property name="compositeCarrierFrequency" value="0.25"/>
    <property name="compositeLinePhase" value="0"/>
    <property name="compositeChromaBandwidth" value="0.01"/>
        <property name="dummy" value="${resourcePath}/images/Dummy.png"/>
        <property name="audio" ref="audio"/>
</component>

</edl>

=== salfter/openemulator/library/Monitors/Studio Monochrome Monitor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE EDL PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" framework="787" label="Studio Monochrome Monitor" image="images/Generic/Monochrome Monitor.png" description="A studio monochrome monitor that can be connected to any composite video source.">
    
    <device id="monochromeMonitor" label="Studio Monochrome Monitor" image="images/Generic/Monochrome Monitor.png">
        <setting ref="monochromeMonitor.monitor" name="videoBrightness" label="Brightness" type="slider" options="-1.0,1.0"/>
        <setting ref="monochromeMonitor.monitor" name="videoContrast" label="Contrast" type="slider" options="0.0,2.0,1.0"/>
        <setting ref="monochromeMonitor.monitor" name="videoSaturation" label="Saturation" type="slider" options="0.0,2.0,1.0"/>
        <setting ref="monochromeMonitor.monitor" name="videoHue" label="Hue" type="slider" options="-0.5,0.5,0.0"/>
        <setting ref="monochromeMonitor.monitor" name="videoHorizontalCenter" label="Horizontal Center" type="slider" options="-0.1,0.1"/>
        <setting ref="monochromeMonitor.monitor" name="videoHorizontalSize" label="Horizontal Size" type="slider" options="0.85,1.25"/>
        <setting ref="monochromeMonitor.monitor" name="videoVerticalCenter" label="Vertical Center" type="slider" options="-0.1,0.1"/>
        <setting ref="monochromeMonitor.monitor" name="videoVerticalSize" label="Vertical Size" type="slider" options="0.85,1.25"/>
        <setting ref="monochromeMonitor.monitor" name="videoBandwidth" label="Video Bandwidth" type="slider" options="0.0,7159090.0"/>
        <setting ref="monochromeMonitor.monitor" name="displayBarrel" label="Barrel" type="slider" options="0.0,1.0"/>
        <setting ref="monochromeMonitor.monitor" name="displayScanlineLevel" label="Scanline Level" type="slider" options="0.0,1.0"/>
        <setting ref="monochromeMonitor.monitor" name="displayPersistence" label="Persistence" type="slider" options="0.0,1.0"/>
        <setting ref="monochromeMonitor.monitor" name="displayCenterLighting" label="Center Lighting" type="slider" options="0.0,1.0"/>
        <setting ref="monochromeMonitor.monitor" name="displayLuminanceGain" label="Luminance Gain" type="slider" options="1.0,2.0"/>
    </device>
    <connector id="monochromeMonitor.connector" type="Composite Video Port">
        <inlet ref="monochromeMonitor.monitor" property="controlBus" outletRef="controlBus"/>
    </connector>
    <component id="monochromeMonitor.monitor" class="Monitor">
        <property name="device" ref="monochromeMonitor"/>
        <property name="controlBus" ref=""/>
        <property name="videoDecoder" value="Monochrome"/>
        <property name="videoBrightness" value="0.15"/>
        <property name="videoContrast" value="0.8"/>
        <property name="videoSaturation" value="1.45"/>
        <property name="videoHue" value="0.27"/>
        <property name="videoHorizontalCenter" value="0"/>
        <property name="videoHorizontalSize" value="1.05"/>
        <property name="videoVerticalCenter" value="0"/>
        <property name="videoVerticalSize" value="1.05"/>
        <property name="videoBandwidth" value="6000000"/>
        <property name="displayBarrel" value="0.1"/>
        <property name="displayScanlineLevel" value="0.5"/>
        <property name="displayPersistence" value="0"/>
        <property name="displayCenterLighting" value="0.5"/>
        <property name="displayLuminanceGain" value="1.5"/>
    </component>
    
</edl>

=== salfter/openemulator/library/Apple II/Apple II Super Serial Card.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" label="Apple II Super Serial Card" image="images/Apple/Apple II Super Serial Card.png" description="The Apple II Super Serial Card is the most commonly used RS-232 serial interface card on Apple II computers. It is usually installed in slot 2.">

<device id="appleSSC" label="Apple II Super Serial Card" image="images/Apple/Apple II Super Serial Card.png">
    <setting ref="appleSSC.io" name="mode" label="Mode" type="select" options="Communications,Printer"/>
    <setting ref="appleSSC.io" name="baudRate" label="Baud Rate" type="select" options="50,75,110,135,150,300,600,1200,1800,2400,3600,4800,7200,9600,19200"/>
    <setting ref="appleSSC.io" name="dataBits" label="Data Bits" type="select" options="7,8"/>
    <setting ref="appleSSC.io" name="stopBits" label="Stop Bits" type="select" options="1,2"/>
    <setting ref="appleSSC.io" name="parity" label="Parity" type="select" options="None,Even,Odd"/>
    <setting ref="appleSSC.io" name="autoLFAfterCR" label="Auto LF After CR" type="checkbox"/>
    <setting ref="appleSSC.io" name="interrupts" label="Enable Interrupts" type="checkbox"/>
    <setting ref="appleSSC.io" name="charactersPerLine" label="Characters per Line" type="select" options="40,72,80,132"/>
    <setting ref="appleSSC.io" name="delayAfterCR" label="Delay After CR" type="checkbox"/>
</device>
<connector id="appleSSC.connector" type="Apple II Slot"/>
<port id="appleSSC.port" ref="" type="RS-232 Port" group="peripherals" label="Serial Port" image="images/Connectors/DE9 Male.png">
    <inlet ref="appleSSC.io" property="port" outletRef="io"/>
</port>
<component id="appleSSC.io" class="AppleIISuperSerialCard">
    <property name="port" ref=""/>
    <property name="mode" value="0"/>
    <property name="baudRate" value="9600"/>
    <property name="dataBits" value="1"/>
    <property name="stopBits" value="1"/>
    <property name="parity" value="0"/>
    <property name="autoLFAfterCR" value="0"/>
    <property name="interrupts" value="0"/>
    <property name="charactersPerLine" value="0"/>
    <property name="delayAfterCR" value="0"/>
</component>
<component id="appleSSC.memory" class="ROM">
    <property name="image" data="${resourcePath}/roms/Apple/341-0065-A.bin"/>
</component>

</edl>

=== salfter/openemulator/library/Generic/Terminal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" label="Terminal" image="images/Generic/Terminal.png" description="A generic terminal that can be connected to any RS-232 port.">

<device id="terminal" label="Terminal" image="images/Generic/Terminal.png">
</device>
<connector id="terminal.connector" type="RS-232 Port"/>
<component id="terminal.io" class="Terminal">
    <property name="device" ref="terminal"/>
    <property name="charset" ref="terminal.charset"/>
    <property name="width" value="24"/>
    <property name="height" value="40"/>
</component>
<component id="terminal.charset" class="CharsetLoader">
    <property name="format" value="Signetics"/>
    <property name="image" src="${resourcePath}/roms/Signetics/Signetics 2513 Video ROM.bin"/>
</component>

</edl>

=== salfter/openemulator/devices/Apple Disk II Drive.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edl PUBLIC "-//OPENEMULATOR//DTD EDL 1.0//EN" "http://www.openemulator.org/DTD/edl-1.0.dtd">
<edl version="1.0" type="Disk Drives" label="Disk II Drive 1" image="Apple Disk II Drive.png">

<device id="diskII" type="Storage" label="Apple Disk II" image="images/apple2/Apple Disk II Drive.png" />
<connector id="diskII.connector" type="AppleIIDisk" label="Apple Disk II Slot Connector" />
<setting ref="diskII.drive" property="lock" type="checkbox" label="Lock Disk Drive" />
<component id="diskII.drive" class="AppleDiskII">
    <property name="image" value=" /Users/mressl/test2.dsk" />
    <property name="lock" value="0" />
    <property name="rpm" value="300.0" />
    <property name="rpmVariance" value="1.0" />
    <property name="soundSpin" src="${resourcePath}/sounds/Apple Disk II Spin.wav" />
    <property name="soundArm" src="${resourcePath}/sounds/Apple Disk II Arm.wav" />
    <property name="soundStop" src="${resourcePath}/sounds/Apple Disk II Stop.wav" />
    <property name="soundShake" src="${resourcePath}/sounds/Apple Disk II Shake.wav" />
</component>

</edl>
