=== salfter/openemulator/doc/DeviceList-1.0.dtd
<!ELEMENT DeviceList (Device+)>
<!ATTLIST DeviceList version CDATA "1.0">

<!ELEMENT Device (ConnectorList?,PortList?,ComponentList)>
<!ATTLIST Device class CDATA #REQUIRED>
<!ATTLIST Device id CDATA #IMPLIED>
<!-- type is "Core" for a computer or "Expansion" for an add-on -->
<!ATTLIST Device type (Core|Expansion) #REQUIRED>
<!-- platform is a label for listing compatible expansions -->
<!ATTLIST Device platform CDATA #REQUIRED>
<!-- group is a label for listing related resources -->
<!ATTLIST Device group CDATA #REQUIRED>
<!ATTLIST Device isMountable (0|1) "0">
<!ATTLIST Device description CDATA #IMPLIED>
<!ATTLIST Device image CDATA #IMPLIED>

<!ELEMENT ConnectorList (Connector+)>
<!ELEMENT Connector EMPTY>
<!ATTLIST Connector idref CDATA #REQUIRED>
<!ATTLIST Connector type CDATA #REQUIRED>

<!ELEMENT PortList (Port+)>
<!ELEMENT Port EMPTY>
<!ATTLIST Port idref CDATA #REQUIRED>
<!ATTLIST Port parameter CDATA #REQUIRED>
<!ATTLIST Port type CDATA #REQUIRED>
<!ATTLIST Port title CDATA #REQUIRED>

<!ELEMENT ComponentList (Component+)>
<!ELEMENT Component (Parameter*)>
<!ATTLIST Component class CDATA #REQUIRED>
<!ATTLIST Component id ID #IMPLIED>

<!ELEMENT Parameter EMPTY>
<!ATTLIST Parameter name CDATA #REQUIRED>
<!ATTLIST Parameter value CDATA #REQUIRED>

=== salfter/openemulator/templates/Host.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DeviceList PUBLIC "-//OPENEMULATOR//DTD DEVICELIST 1.0//EN" "http://www-personal.umich.edu/~mressl/DTDs/DeviceList-1.0.dtd">
<DeviceList version="1.0">
<Device type="Host">
    <ComponentList>
    <Component class="AudioController" />
    <Component class="DiskController" />
    <Component class="EthernetController" />
    <Component class="EventController" />
    <Component class="JoystickController" />
    <Component class="KeyboardController" />
    <Component class="MouseController" />
    <Component class="ResourceController" />
    <Component class="SerialController" />
    <Component class="TabletController" />
    <Component class="VideoController" />
    <Component class="WavePlayer" />
    </ComponentList>
</Device>
</DeviceList>

=== salfter/openemulator/templates/Apple 3.5 Floppy Disk Drive Interface Card.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DeviceList PUBLIC "-//OPENEMULATOR//DTD DEVICELIST 1.0//EN" "http://www-personal.umich.edu/~mressl/DTDs/DeviceList-1.0.dtd">
<DeviceList version="1.0">
<Device type="Expansion" name="Apple 3.5 inch Floppy Disk Drive Interface Card" platform="Apple II" group="Disk Drive" image="Apple 3.5 Floppy Disk Drive Interface Card.png" description="">
    <ComponentList>
    <Component class="Apple35FloppyDiskDriveInterfaceCard">
        <Connection port="Apple II Slot" />
        <Parameter name="Port 1" port="Apple SmartPort" />
        <Parameter name="Port 2" port="Apple SmartPort" />
        <Parameter name="Port 3" port="Apple SmartPort" />
        <Parameter name="Port 4" port="Apple SmartPort" />
    </Component>
    </ComponentList>
</Device>
</DeviceList>
