=== salfter/openemulator/doc/dml-1.0.dtd
<!ELEMENT dml (device+)>
<!ATTLIST dml version CDATA "1.0">

<!ELEMENT device (component+)>
<!ATTLIST device name CDATA #REQUIRED>
<!ATTLIST device platform CDATA #REQUIRED>
<!ATTLIST device group CDATA #REQUIRED>
<!ATTLIST device label CDATA #REQUIRED>
<!ATTLIST device description CDATA #IMPLIED>
<!ATTLIST device image CDATA #IMPLIED>

<!ELEMENT component (property+)>
<!ATTLIST component class CDATA #REQUIRED>
<!ATTLIST component name CDATA #IMPLIED>
<!ATTLIST component outlet CDATA #IMPLIED>

<!ELEMENT property EMPTY>
<!ATTLIST property key CDATA #REQUIRED>
<!ATTLIST property type (number|string|component) #REQUIRED>
<!ATTLIST property value CDATA #REQUIRED>
<!ATTLIST property inlet CDATA #IMPLIED>
<!ATTLIST property label CDATA #IMPLIED>

=== salfter/openemulator/xml/Host.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dml PUBLIC "-//OPENEMULATOR//DTD DML 1.0//EN" "http://www.openemulator.org/DTDs/dml-1.0.dtd">
<dml version="1.0">
<device class="Host" type="host" platform="" group="">
    <components>
    <component class="AudioController" />
    <component class="DiskController" />
    <component class="EthernetController" />
    <component class="EventController" />
    <component class="JoystickController" />
    <component class="KeyboardController" />
    <component class="MouseController" />
    <component class="ResourceController" />
    <component class="SerialController" />
    <component class="TabletController" />
    <component class="VideoController" />
    <component class="WavePlayer" />
    </components>
</device>
</dml>

=== salfter/openemulator/templates/IBM PC.emulation/info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dml PUBLIC "-//OPENEMULATOR//DTD DML 1.0//EN" "http://www.openemulator.org/DTDs/dml-1.0.dtd">
<dml version="1.0" label="IBM PC 5150" image="IBM PC 5150.png" description="" group="PC">
<device name="host">
    <component name="events" class="EventController">
        <property name="runTime" value="0.0" />
    </component>
    <component name="audio" class="AudioController">
        <property name="volume" value="1.0" />
    </component>
    <component name="video" class="VideoController">
    </component>
    <component name="keyboard" class="KeyboardController">
    </component>
    <component name="joystick" class="JoystickController">
    </component>
    <component name="mouse" class="MouseController">
    </component>
    <component name="tablet" class="TabletController">
    </component>
</device>

<device name="dev0" label="IBM PC">
</device>

</dml>

=== salfter/openemulator/xml/Apple I.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dml PUBLIC "-//OPENEMULATOR//DTD DML 1.0//EN" "http://www.openemulator.org/DTDs/dml-1.0.dtd">
<dml version="1.0">
<device class="Apple I" type="core" platform="Apple I" group="Apple I" description="The Apple I was Apple's first product. It was a fully assembled circuit board containing about 30 chips, but users still had to add a case, power supply, keyboard, and display. One major difference sets the Apple I apart â€” it was the first personal computer to use a keyboard." image="$RESOURCES/Apple I.png">
    <components>
    <component class="AppleIFloatingBus" />
    <component class="AppleIEventController">
        <property name="eventController" value="Host::EventController" />
    </component>
    <component class="MOS6502">
        <property name="mmu" value="AppleIMMU" />
    </component>
    <component class="AppleIMMU" />
    <component class="AppleIMemory">
        <property name="mmu" value="AppleIMMU" />
        <property name="memoryImage" value="$PROFILE/Apple I RAM.bin" />
        <property name="resourceController" value="Host::ResourceController" />
    </component>
    <component class="AppleIROM">
        <property name="mmu" value="AppleIMMU" />
        <property name="memoryImage" value="$RESOURCES/Apple I ROM.bin" />
        <property name="resourceController" value="Host::ResourceController" />
    </component>
    <component class="AppleISlotController">
        <port type="Apple I Slot" name="slotR" label="Slot R" />
        <port type="Apple I Slot" name="slotS" label="Slot S" />
        <port type="Apple I Slot" name="slotT" label="Slot T" />
    </component>
    <component class="AppleIVIA">
        <property name="mmu" value="AppleIMMU" />
        <property name="keyboardController" value="Host::KeyboardController" />
    </component>
    <component class="AppleIVideoController">
        <property name="videoController" value="Host::VideoController" />
        <property name="characterSet" value="/Resources/Apple II Video ROM.bin" />
    </component>
    </components>
</device>
</dml>
